#!/usr/bin/env node
/**
 * Meli 15-day Top 5 Report Generator
 *
 * Reads `data/history/{cat}-{slug}.jsonl` (one line per day, schema v2)
 * and emits a markdown file with one table per category:
 *   rows = #1..#5 ranks
 *   cols = last 15 days (left = today, right = 15 days ago)
 *   cells = "🟦 Brand Model R$xxx" with brand-color emoji prefix
 *
 * Usage:
 *   node generate-report.js --out /tmp/meli-15d-report.md
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const ROOT = path.resolve(__dirname, '..');
const HISTORY_DIR = path.join(ROOT, 'data', 'history');
const CATEGORIES_PATH = path.join(ROOT, 'config', 'categories.json');

const WINDOW_DAYS = 15;
const TOP_N = 5;

const CATEGORY_ORDER = [
  'MLB1055',     // 手机（纯手机）
  'MLB135384',   // 智能手表（纯手表）
  'MLB196208',   // 耳机（音频）
  'MLB99889',    // 平板（纯平板）
  'MLB1051',     // 手机大类
  'MLB417704',   // 智能穿戴大类
  'MLB1664',     // 耳机 Gaming
  'MLB91757',    // 平板大类
];

const BRAND_EMOJI = {
  huawei: '🟥',
  honor: '🟨',
  samsung: '🟦',
  motorola: '🟧',
  xiaomi: '🟩', mi: '🟩', redmi: '🟩', poco: '🟩',
  apple: '🟪',
  realme: '🟫',
  jbl: '⬛', soundcore: '⬛', anker: '⬛',
  amazfit: '⬛', garmin: '⬛', sony: '⬛',
  bose: '⬛', logitech: '⬛', edifier: '⬛',
};

function emojiFor(brand) {
  if (!brand) return '⬜';
  return BRAND_EMOJI[brand.toLowerCase()] ?? '⬜';
}

function shortName(it) {
  const brand = it.brand ?? '';
  const tail = (it.line ?? it.model ?? '').trim();
  let s;
  if (tail.toLowerCase().startsWith(brand.toLowerCase()) && brand) {
    s = tail;
  } else {
    s = [brand, tail].filter(Boolean).join(' ').trim();
  }
  if (!s) return (it.title ?? '').slice(0, 24);
  return s.length > 24 ? s.slice(0, 24) : s;
}

function fmtPriceBR(p) {
  if (p == null) return '—';
  return 'R$ ' + Math.round(p).toLocaleString('de-DE');
}

function fmtDateMD(iso) {
  const [, m, d] = iso.split('-');
  return `${m}-${d}`;
}

function isNewSchema(line) {
  return line.items?.[0] && 'catalog_product_id' in line.items[0];
}

async function readHistory(catId, slug) {
  const file = path.join(HISTORY_DIR, `${catId}-${slug}.jsonl`);
  const raw = await fs.readFile(file, 'utf8');
  const lines = raw.split('\n').filter(Boolean).map((l) => JSON.parse(l));
  return lines.filter(isNewSchema).sort((a, b) => a.date.localeCompare(b.date));
}

function buildCategoryTable(cat, history) {
  const days = history.slice(-WINDOW_DAYS).reverse();
  if (days.length === 0) {
    return `## ${cat.name_zh} / ${cat.name_en}\n\n_无 schema v2 数据可显示_\n`;
  }

  const dateRange = `${days[days.length - 1].date} → ${days[0].date}`;
  const headerRow = '| Rank \\ Date | ' + days.map((d) => fmtDateMD(d.date)).join(' | ') + ' |';
  const sepRow = '|---|' + days.map(() => '---').join('|') + '|';

  const rows = [];
  for (let rank = 1; rank <= TOP_N; rank++) {
    const cells = days.map((d) => {
      const it = d.items.find((x) => x.rank === rank);
      if (!it) return '—';
      const emoji = emojiFor(it.brand);
      const name = shortName(it);
      const price = fmtPriceBR(it.min_price);
      return `${emoji} ${name} ${price}`;
    });
    rows.push(`| **#${rank}** | ${cells.join(' | ')} |`);
  }

  return [
    `## ${cat.name_zh} / ${cat.name_en}`,
    `_Source ${cat.id} · ${days.length} days (${dateRange}) · 价格 = catalog \`min_price\`_`,
    '',
    headerRow,
    sepRow,
    ...rows,
    '',
  ].join('\n');
}

function buildPreface(allCats, latestDate) {
  return [
    `# 📊 Meli 15日 Top 5 榜单 / 15-Day Top 5 Leaderboard`,
    ``,
    `**截至 / As of**: ${latestDate} · 巴西时间 Brazil time`,
    '**数据源 / Source**: Mercado Livre OAuth API (`/highlights` + `/products` + `/items`)',
    '**价格字段 / Price field**: `min_price` — catalog 下多卖家真实最低价',
    ``,
    `**品牌色块图例 / Brand color legend**:`,
    `🟥 Huawei · 🟨 Honor · 🟦 Samsung · 🟧 Motorola · 🟩 Xiaomi 家族 (Mi/Redmi) · 🟪 Apple · 🟫 Realme · ⬛ JBL/Soundcore/Anker/Amazfit/Garmin · ⬜ 其他/小品牌`,
    ``,
    `---`,
    ``,
  ].join('\n');
}

function buildFooter() {
  return [
    `---`,
    ``,
    `_自动生成 / Auto-generated by GitHub Actions · 每天巴西时间 7:30 抓取 · 8:00 前送达_`,
    `_Repo: HuijieL/meli-price-tracker · 设计 Design by Ben LI Huijie_`,
    ``,
  ].join('\n');
}

function parseArgs(argv) {
  const args = { out: '/tmp/meli-15d-report.md' };
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === '--out') args.out = argv[++i];
  }
  return args;
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const catsRaw = JSON.parse(await fs.readFile(CATEGORIES_PATH, 'utf8'));
  const catsById = Object.fromEntries(catsRaw.categories.map((c) => [c.id, c]));

  const sections = [];
  let latestDate = '';

  for (const catId of CATEGORY_ORDER) {
    const cat = catsById[catId];
    if (!cat) continue;
    const history = await readHistory(cat.id, cat.slug);
    if (history.length > 0) {
      const lastDate = history[history.length - 1].date;
      if (lastDate > latestDate) latestDate = lastDate;
    }
    sections.push(buildCategoryTable(cat, history));
  }

  const md = [
    buildPreface(catsRaw.categories, latestDate || '—'),
    sections.join('\n'),
    buildFooter(),
  ].join('\n');

  await fs.writeFile(args.out, md, 'utf8');
  console.log(`✅ Wrote ${args.out} (${md.length} bytes, ${sections.length} categories)`);
}

const invokedDirectly =
  process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (invokedDirectly) {
  main().catch((err) => {
    console.error(err);
    process.exit(1);
  });
}

export { buildCategoryTable, emojiFor, shortName, fmtPriceBR };
